- hosts: localhost
  gather_facts: no

  vars_files:
    - ./vars_1_encrypted.yml
    - ./vars_2_encrypted.yml

  tasks:

    - name: debug msg with only a sensitive var
      debug:
        msg: "{{ sensitive_var_1 }}"

    - name: debug msg with text and a sensitive var
      debug:
        msg: "this message contains a sensitive data {{ sensitive_var_1 }}"

    - name: fail task with a msg text and a sensitive var
      fail:
        msg: "The system may not be provisioned according to the CMDB {{ sensitive_var_2 }} status."